language: ruby
before_install:
  - sudo apt-get install libsqlite3-dev
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-19mode
  - rbx-19mode
  # - 2.0.0
matrix:
  allow_failures:
    - rvm: jruby-19mode
script: rake test
